### ISSUE TITLE
Problem migrating from DZGA to DZGA-Flash with Google connection

### ISSUE THREAD

**Issue by xvisor16** [DewGew/DZGA-Flask#113]
Hi I am having difficulties migrating. First of I tried migrating since DZGA stopped working yesterday and I saw 403 and 404 errors in the log. Did some searching and suggestions were to update DZGA. Only then I found out it's archived so saw the new DZGA-Flask solution. I disabled DZGA and installed DZGA-Flask as per Wiki.

Now with Google Assistent disabled I see and can use all my devices in the Dashboard and Device overview. I created a new key for my existing project and uploaded it and used the same clientid and secret as used in DZGA. But if I enable Google Assistent and try to sync my devices I get this error:

```
Starting new HTTP connection (1): 192.168.68.97:80
http://192.168.68.97:80 "GET /json.htm?type=command&param=getversion HTTP/1.1" 200 328
Starting new HTTPS connection (1): homegraph.googleapis.com:443
https://homegraph.googleapis.com:443 "POST /v1/devices:requestSync HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/DZGA-Flask/modules/api.py", line 152, in gateway
    rs.call_homegraph_api('sync', {"agentUserId": flask_login.current_user.username})
  File "/root/DZGA-Flask/modules/reportstate.py", line 111, in call_homegraph_api
    r.raise_for_status()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:requestSync
```

```
If I try to test from Google Actions it says it can't reach my home and the log says:
Traceback (most recent call last):
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/DZGA-Flask/smarthome.py", line 278, in fulfillment
    user_id = flask_login.current_user.username
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask_login/login_manager.py", line 378, in _load_user
    user = self._load_user_from_request(request)
  File "/root/DZGA-Flask/env/lib/python3.9/site-packages/flask_login/login_manager.py", line 441, in _load_user_from_request
    user = self._request_callback(request)
  File "/root/DZGA-Flask/smarthome.py", line 77, in request_loader
    if user.username:
AttributeError: 'NoneType' object has no attribute 'username'
```

I've tried creating 2 new projects, actions and keys as per Wiki but still the same error :(
What did I miss or am I running into a bug?

Regards Peter

**Comment by ayasystems** [comment]
you need to pair again your project into google home app

**Comment by xvisor16** [comment]
> you need to pair again your project into google home app

Thanks for the answer but I tried that multiple times, i get to the login screen from DZGA, login, it redirects me back to the Google Home app and then says it can't reach my project and asks to try again. When i check the DZGA log i see this:

`2024-07-13 16:11:41 generated code
2024-07-13 16:11:43 request:
{
  "inputs": [
    {
      "intent": "action.devices.SYNC"
    }
  ],
  "requestId": "6614160712180923669"
}
2024-07-13 16:11:43 Starting new HTTP connection (1): 192.168.68.97:80
2024-07-13 16:11:43 http://192.168.68.97:80 "GET /json.htm?type=command&param=getdevices&plan=0&filter=all&used=true HTTP/1.1" 200 18505
2024-07-13 16:11:45 Retreiving devices from domoticz
2024-07-13 16:11:45 Devices is saved in admin_devices.json in config folder
2024-07-13 16:11:46 response: 
{
  "requestId": "6614160712180923669",
  "payload": {
    "agentUserId": "admin",
    "devices": [
list of all my 177 devices, etc
]....`

But nothing tells me what went wrong or what to fix. It says "generated code" in the logs so i'd say it connected well but that it.

**Comment by xvisor16** [comment]
I've got a little further, the initial sync fails, so it doesn't go through the whole path making it look like my pairing is out. But when making a small selection of devices to synchronise to Google home, it does work, and everything goes through and is fine. So there is a device in my list that has a problem when doing the initial sync. The thing is, I can't figure out which one... Is there a debug mode available or could logging be added so that it shows on which device the whole sync fails so I can fix this. This could be extremely helpful to others too!

**Comment by Xavier82** [comment]
yes there is:
   
  
    
   
  
   https://developers.home.google.com/cloud-to-cloud/guides
   
  
    
   
  
   check your device type and the trait.
   
  
   By click ondevice type you can test by a request.
   
  
    
   
  
   and also:
   
  
    
   
  
   https://developers.home.google.com/cloud-to-cloud/intents/errors-exceptions
   
  
    
   
  
   gope this helps!
   
   
   
    Op 16-05-2025 17:50 CEST schreef xvisor16 ***@***.***>:
    
   
     
    
   
     
    
   
    xvisor16 left a comment (DewGew/DZGA-Flask#113)
    
   I've got a little further, when making a small selection of devices to synchronise to Google home, it does work. So probably there is a device in my list that has a problem when doing the initial sync. The thing is can't figure out which one... Is there a debug mode available or could logging be added so that it shows on which device the whole sync fails so I can fix this. This could be very helpful to others too!

**Comment by xvisor16** [comment]
Hi @Xavier82, Thanks, I have been looking at that, but I don't see how this helps me find out which device causes the problem, if any...? I have posted everything that I can find in the logging in this thread, but I can't find anything that would help me find my problem. I just don't understand why the App doesn't report back what failed on what, instead of just a general error?

**Comment by Xavier82** [comment]
To be sure....
   
  
    
   
  
   You have added the devices in Domoticz under the created user for DZGA?
   
  
   Do you see the Domoticz devices in DZGA?
   
  
    
   
  
   What do you see in the logging of DZGA?
   
  
   Any 400 error code? or other?
   
  
    
   
  
   What kind of devices (device types) do you want to sync to Google Home to control?
   
  
    
   
  
   Are you sure the smart-key.json file is uploaded correctly in DZGA?
   
  
    
   
  
   Are you sure you use the correct project in Google Console? (This is the most common issue)
   
   
   
    Op 19-05-2025 11:22 CEST schreef xvisor16 ***@***.***>:
    
   
     
    
   
     
    
   
    xvisor16 left a comment (DewGew/DZGA-Flask#113)
    
   Hi @Xavier82, Thanks, I have been looking at that, but I don't see how this helps me find out which device causes the problem, if any...? I have posted everything that I can find in the logging in this thread, but I can't find anything that would help me find my problem. I just don't understand why the App doesn't report back what failed on what, instead of just a general error?
